#+OPTIONS: toc:2

* Installation

** Grafical (Reccommended)

Install through a USB flashed drive and then choose the minimal.
You should skip all the nonesense for the partitioning below.
Once in the terminal run

#+begin_src
  sudo loadkeys -v dvorak # (Optional) Set dvorak for the session
  nmcli device wifi connect <ssid> password <password> # To connect to the internet - check with ping google.com
  nix-shell -p git micro ripgrep # Create a nix shell with basic software to modify and change the repo
  git clone https://github.com/benkio/nix-config.git # Clone this repo
  cd nix-config
  sudo nixos-rebuild build --flake .#nixos # Build it
  sudo nixos-rebuild switch --flake .#nixos # If previous command succeded, apply the new configuration
#+end_src

** Minimal NixOs Commands

  Edit: this was done long ago, it might be outdated/unecessary now
  Commands to run on startup to install nixos and add the configuration

#+begin_src
nix-env -i git
git clone https://github.com/benkio/nix-config.git
cd nix-config/

sudo su

# MBR
parted /dev/sda -- mklabel msdos
parted /dev/sda -- mkpart primary 1MiB -8GiB
parted /dev/sda -- mkpart primary linux-swap -8GiB 100%

# UEFI
parted /dev/sda -- mklabel gpt
parted /dev/sda -- mkpart primary 512MiB -8GiB
parted /dev/sda -- mkpart primary linux-swap -8GiB 100%
parted /dev/sda -- mkpart ESP fat32 1MiB 512MiB
parted /dev/sda -- set 3 esp on

mkfs.ext4 -L nixos /dev/sda1
mkswap -L swap /dev/sda2
swapon /dev/sda2
mkfs.fat -F 32 -n boot /dev/sda3        # (for UEFI systems only)
mount /dev/disk/by-label/nixos /mnt
mkdir -p /mnt/boot                      # (for UEFI systems only)
mount /dev/disk/by-label/boot /mnt/boot # (for UEFI systems only)
nixos-generate-config --root /mnt
cp configuration.nix /mnt/etc/nixos/
nixos-install
reboot
#+end_src

remember the root password
remove the nixos image from the drive

* Set Unstable Channel

If you want the unstable channel (latest changes) you need to remove the sudo channel for nixos and put the unstable

#+begin_src
  # flakes are already pinned in flake.lock
  nix flake update
  sudo nixos-rebuild switch --flake .#nixos # If needed, rebuild with the latest lock file
#+end_src

* Home Manager Installation

#+begin_src shell
# Build and switch from flake-based home configuration
cd ~/nix-config
home-manager switch --flake .#benkio@macos
#+end_src

log off and in

#+begin_src shell
  # Change it to the right host config with --flake
  cd ~/nix-config
  home-manager switch --flake .#benkio@nixos
#+end_src

* MacOs - Darwin-nix

  For installation of nix-darwin you can switch directly from this flake:

  #+begin_src shell
cd ~/nix-config
sudo darwin-rebuild switch --flake .#macos
  #+end_src

* Post Installation Work

Despite the effort to reduce this there are things you need to do manually

** Setup Github SSH and GPG keys

  Go into Bitwarden, you should see a note about github ssh/gpg
  keys. There you can find the content of the 2 files you need to
  setup. These are the commands you should run. Repeat for every account/key

#+begin_src shell
  mkdir ~/.ssh
  cd ~/.ssh
  touch id_rsa
  touch id_rsa.pub
  # Go to Bitwarden, copy and paste the SSH Private and Public keys. eg with vi
  chmod 600 ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa.pub
  # Go to Bitwarden, copy and paste the GPG key into private.key file
  gpg --import private.key
#+end_src

** Finish/check Emacs Configuration

 If no ~.emacs.d~ folder is not found in your home, then the
 emacs-config repo is downloaded and put in place, but with a
 different branch (~fetchgit~). After setting up the SSH keys from
 Github, be sure to run the following commands

#+begin_src shell
  # Execute after setting the ssh key from bitwarden
  git pull origin main
  git checkout -f main
  git clean -fx
  git branch -D fetchgit
  # Run generation of treesitter grammars
#+end_src

** Work Setup

There are 2 work files named ~work.nix~ that are specific for your workplace.
There might be some GPG key to be specified there, email, extra ++homebrew+ packages etc
Go there and review.
