{
  config,
  pkgs,
  lib,
  ...
}:

###############################################################################
#                   Packages without specific configuration                   #
###############################################################################

{
  # Remove linux application, but keeping and merging terminal utilities from nixos system configuration
  home.packages = with pkgs; [
    # BROKEN haskellPackages.ghc-mod
    act
    amule
    autoconf
    aws-vault
    bitwarden
    bleachbit
    bluez
    brightnessctl
    btop
    calibre
    copyq
    coursier
    corefonts
    curl
    dmenu
    docker
    docker-compose
    dust
    elmPackages.elm
    evince
    exfatprogs
    eza
    fd
    feh
    ffmpeg-full
    gcc
    ghc
    ghcid
    gitui
    glibcLocales
    gparted
    guvcview
    haskellPackages.apply-refact
    haskellPackages.fourmolu
    haskellPackages.hoogle
    hexchat
    hlint
    html-tidy
    hurl
    id3v2
    imagemagick
    jack2
    jdk
    k9s
    kmetronome
    kubectl
    lame
    libsForQt5.kdenlive
    lilypond
    litecli
    lshw
    lsof
    lychee
    maestral
    maestral # dropbox alternative
    magic-wormhole
    mediainfo
    megasync
    mermaid-cli
    nethogs
    nettools
    nix-prefetch-scripts
    nixfmt-rfc-style
    nmap
    ormolu
    pamixer
    parted
    pavucontrol
    pciutils
    picard
    playerctl
    procs
    psmisc
    purescript
    qjackctl
    reaper
    ripgrep
    rustup
    scala
    scala-cli
    scalafmt
    spark
    slack
    sound-juicer
    sqlite
    stack
    teamviewer
    telegram-desktop
    termdown
    tldr
    tunnelto
    unetbootin
    unipicker
    unrar
    unzip
    usbutils
    uutils-coreutils
    vlc
    watchexec
    wget
    xclip
    xorg.setxkbmap
    zip
    zoom-us
  ];
}
