name: macOS CI

on:
  push:
    branches:
      - "**"

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        env:
          NIX_FIRST_BUILD_UID: "331"
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Install omnix
        run: nix profile install github:NixOS/nixpkgs/nixpkgs-unstable#omnix
      - name: Home-manager CI
        run: om ci run ./flake/home
