name: Scala CI

on:
  push:
    branches:
      - "**"

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install nixpkgs, home-manager & nixfmt
        run: |
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update
          nix-env -iA nixfmt-rfc-style -f '<nixpkgs>'
          export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
          nix-shell '<home-manager>' -A install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Formatting
        run: |
          echo this workflow was triggered by ${{github.actor}}
          find . -name '*.nix' | xargs nixfmt -c
      - name: Darwin Install & build
        run: |
          nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
          nix-channel --update
          export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
          echo $NIX_PATH
          nix-build '<darwin>' -A darwin-rebuild
          ./result/bin/darwin-rebuild switch -I ./MacOs/system/darwin-configuration.nix
      - name: Home-manager build
        run: |
          home-manager build -I ./MacOs/home/home.nix
