name: Scala CI

on:
  push:
    branches:
      - "**"

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install channels + nixfmt
        run: |
          # Add nixpkgs and darwin channels for the user
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
          nix-channel --add https://github.com/nix-darwin/nix-darwin/archive/master.tar.gz darwin
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update
          # Install nixfmt
          nix-env -iA nixfmt-rfc-style -f '<nixpkgs>'
          # Set NIX_PATH explicitly to include darwin and nixpkgs
          echo "NIX_PATH=nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs:darwin=$HOME/.nix-defexpr/channels/darwin${NIX_PATH:+:}$NIX_PATH" >> $GITHUB_ENV
          export NIX_PATH=nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs:darwin=$HOME/.nix-defexpr/channels/darwin${NIX_PATH:+:}$NIX_PATH
      - name: Install Home-manager
        run: nix-shell '<home-manager>' -A install
      - name: Checkout
        uses: actions/checkout@v3
      - name: Formatting
        run: |
          echo this workflow was triggered by ${{github.actor}}
          find . -name '*.nix' | xargs nixfmt -c
      - name: Darwin Install & build
        run: |
          echo $NIX_PATH
          nix-build '<darwin>' -A darwin-rebuild
          ./result/bin/darwin-rebuild switch -I ./MacOs/system/darwin-configuration.nix
      - name: Home-manager build
        run: |
          echo $NIX_PATH
          home-manager build -I ./MacOs/home/home.nix
